# This GitHub Action will build the sphinx documentation and publsih it to AWS S3

name: Build Sphinx Documentation

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "make html"
